### ISSUE TITLE
Weather API Documentation

### ISSUE THREAD

**Issue by michaelkhanda** [KilimoGuard/kilimoGuard_Backend#18]

**Comment by KEEGANTE** [comment]
### **OpenWeatherMap API Documentation**

![image](https://github.com/user-attachments/assets/16fe8a50-0514-4e49-85b5-06ddd07a02ea)

### **1. About OpenWeatherMap**
The OpenWeatherMap API provides weather data for any location in the world, including current weather, forecasts, and historical data. The API is accessible via HTTP requests and returns data in JSON or XML formats. This documentation will cover retrieving key weather data points such as temperature, rainfall, humidity, wind speed, and soil moisture, as well as the process for uploading research documents.

**2. API Key**
To use the OpenWeatherMap API, you need to sign up and get an API key. This key will authenticate your requests to the API.

- **Sign up:** [OpenWeatherMap API](https://openweathermap.org)

- **API Key:** Available in your OpenWeatherMap account after registration.

**3. Base URL**
The base URL for the API is: [https://openweathermap.org/api](url)

**4. Key Data Points**
**4.1 Temperature**

- **Endpoint:** weather
- **Query Parameters:**

> - q (city name, state code, and country code)
> - appid (your API key)
> - units (metric for Celsius, imperial for Fahrenheit)

- **Sample Request:**
**bash: https://api.openweathermap.org/data/2.5/weather?q=Addis Ababa&appid=YOUR_API_KEY&units=metric**

- **Response:**
**JSON:**
`{
    "main": {
        "temp": 20.5
    }
}`

- **Description:** The temp field provides the current temperature in the specified units.

**4.2 Rainfall**

- **Endpoint:** weather
- **Query Parameters:** Same as above
- **Sample Request: https://api.openweathermap.org/data/2.5/weather?q=Nairobi&appid=YOUR_API_KEY
**

- **Response:**
`{
    "rain": {
        "1h": 2.5
    }
}
`
- **Description:** The rain field provides the rainfall volume for the last hour in mm.

**4.3 Humidity**

- **Endpoint:** weather
- **Query Parameters:** Same as above
**Sample Request: https://api.openweathermap.org/data/2.5/weather?q=Cairo&appid=YOUR_API_KEY
**
- **Response: JSON**
`{
    "main": {
        "humidity": 65
    }
}
`
- **Description:** The humidity field provides the current humidity percentage.

**4.4 Wind Speed**

- **Endpoint:** weather
- **Query Parameters:** Same as above
- **Sample Request: https://api.openweathermap.org/data/2.5/weather?q=Accra&appid=YOUR_API_KEY
**
- **Response: JSON**
`{
    "wind": {
        "speed": 3.6
    }
}
`
- **Description:** The wind field provides the current wind speed in meters per second.

**4.5 Soil Moisture**

- **Endpoint:** onecall

- Query Parameters:
> - **lat** (latitude)
> - **lon** (longitude)
> - **exclude** (part of data to exclude, e.g., minutely, hourly)
> - **appid** (your API key)

- **Sample Request: https://api.openweathermap.org/data/2.5/onecall?lat=35.6895&lon=139.6917&exclude=minutely,hourly&appid=YOUR_API_KEY**

- **Response:**
`{
    "current": {
        "soil_moisture": 0.23
    }
}
`
- **Description:** The soil_moisture field provides the current soil moisture level.

**5. Uploading Research Documents**
Currently, OpenWeatherMap API does not support direct uploading of research documents. However, this functionality can be implemented in your application backend, where you store the documents and link the data retrieved from the OpenWeatherMap API.

**6. Error Handling**
The API returns HTTP status codes to indicate the status of the request:

**200 OK:** The request was successful.
**401 Unauthorized:** Invalid API key.
**404 Not Found:** The requested resource could not be found.
**429 Too Many Requests:** The API rate limit has been exceeded.

**7. Rate Limits**
OpenWeatherMap API has rate limits depending on the plan you subscribe to. Free accounts typically have a limit of 60 calls per minute.

**8. Conclusion**
The OpenWeatherMap API is a powerful tool for accessing weather data. This documentation provides a guide for retrieving key weather data points and suggests how to handle additional functionality like uploading research documents through your own systems.

_I also used ChatGPT to do a summary of the document_
