### ISSUE TITLE
Look for API that has weather details based on location

### ISSUE THREAD

**Issue by petermirithu** [KilimoGuard/kilimoGuard_Backend#4]
Key data points:- temperature, rainfall, humidity, wind_speed, soil_moisture

**Comment by KEEGANTE** [comment]
### API that has weather details based on location

**1. OpenWeatherMap**

[https://openweathermap.org/api#current](url)

**Features:** 
Current weather data 

![image](https://github.com/user-attachments/assets/e3ff104c-29dd-4ed6-8ef7-ae452bb35f08)

**Availability:** Data is available in the three formats as stated...
![image](https://github.com/user-attachments/assets/e143ed83-7881-4e58-949b-82f3693e1039)

**CheckList**

- [ ] Temperature 🌤️❄️🌩️
- [ ] Rainfall 🌧️⛈️
- [ ] Humidity ☀️
- [ ] Wind Speed🌪️☁️
- [ ] Soil Moisture 💧🌳

![image](https://github.com/user-attachments/assets/7dd1294e-ae65-4c54-8046-a8f02d7109e8)

**Pricing:**
I would recommend it, though it doesn't have soil moisture 
![image](https://github.com/user-attachments/assets/5fce2cd3-2191-438e-b1b0-a9e752b9ea47)

**Comment by KEEGANTE** [comment]
**API that has weather details based on location**

### 2. Weatherbit

[https://www.weatherbit.io/api](url) 

**API FEATURES:**

- _Current Weather:_
![image](https://github.com/user-attachments/assets/9e738ce4-3548-4234-a70d-84b21c038a12)

Example:
![image](https://github.com/user-attachments/assets/2f0d11f4-5e6a-41f6-93b2-83723d9481df)

- Historical Weather
- Weather Forecasts

**PRICING**
![image](https://github.com/user-attachments/assets/7d733e97-a184-4eb4-abec-4c293de71358)

**Subscription feature comparison**
![image](https://github.com/user-attachments/assets/10bc8a0a-34d6-4552-a06e-5d5a10aafadb)
